name: karigar
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.11.4


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  get: ^4.7.3
  url_launcher: ^6.3.2
  intl: ^0.20.2
  dio: ^5.9.2
  flutter_easyloading: ^3.0.5
  google_fonts: ^8.1.0
  cached_network_image: ^3.4.1
  responsive_framework: ^1.5.1
  auto_size_text: ^3.0.0
  equatable: ^2.0.8
  image_picker: ^1.2.2
  http_parser: ^4.1.2
  mime: ^2.0.0
  talker_dio_logger: ^5.1.17
  ansicolor: ^2.0.3
  logger: ^2.7.0
  provider: ^6.1.5+1
  geolocator: ^14.0.2
  flutter_svg: ^2.3.0
  lottie: ^3.3.3
  animate_do: ^5.1.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    # - assets/icons/
